#!/usr/bin/env bash
PW=$(cat /mnt/e/项目/自动化取证/cases/.wsl_pw | tr -d '\r\n')
SUDO() { echo "$PW" | sudo -S "$@"; }
ANS="/mnt/e/项目/自动化取证/cases/2026FIC电子取证/shared/answers"

# 落盘 C05
cat > "$ANS/C05_main_pc_vpn_port.md" <<'A'
## C05 — 计算机 VPN 软件开放的代理端口

> 分析计算机检材，李安弘电脑vpn软件开放的代理端口为

**答案**: `7897`  **置信度**: 高

### 解析

**识别**: 计算机检材 (Deepin 23.1) 的 root 用户家目录（位于 `_dde_data` 分区 ext4）下找到 Clash Verge Rev：
- 二进制：`/usr/bin/clash-verge`
- systemd 服务：`/etc/systemd/system/multi-user.target.wants/clash-verge-service.service`
- 配置目录：`/root/.local/share/io.github.clash-verge-rev.clash-verge-rev/`

**提取+分析**:
```bash
sudo cat /tmp/pc_data/root/.local/share/io.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml
```

关键字段：
```
# Generated by Clash Verge
mode: rule
mixed-port: 7897        <- HTTP+SOCKS5 混合代理端口
allow-lan: false
ipv6: true
external-controller: ''
```

`mixed-port: 7897` 是 Clash 的 HTTP+SOCKS5 混合代理监听端口，即"VPN 软件开放的代理端口"。

### 不作弊声明
- 数据来源: 检材1 _dde_data 分区
- 工具: cat
- 脚本: scripts/fic_clash_foxmail.sh
A

echo ""
echo "===== 落盘 C05 ====="
ls -la "$ANS"

echo ""
echo "==========================================" 
echo "C02: 邮件 - 找 token 钓鱼邮件"
echo "=========================================="
MAIL_DIR="/tmp/pc_data/home/lha/.local/share/deepin/deepin-mail/imap.163.com/lihongan19851024@163.com/imap"
echo "--- 邮件总数 ---"
SUDO ls $MAIL_DIR/ | wc -l
echo ""
echo "--- 在所有 .eml 中找 token / 钓鱼相关 ---"
SUDO grep -l -i 'token\|钓鱼\|领取\|空投\|airdrop\|free' $MAIL_DIR/*/mail.eml 2>/dev/null | head -10
echo ""
echo "--- 看每封邮件的 Subject + From ---"
SUDO bash -c 'for d in $0/*/; do
  eml=$d/mail.eml
  if [ -f "$eml" ]; then
    echo "--- $d ---"
    head -100 "$eml" | grep -iE "^Subject:|^From:|^Date:" | head -5
  fi
done' "$MAIL_DIR"
