#!/usr/bin/env python3
"""
build_kb_index.py — Auto-regenerate knowledge base INDEX files.

Scans `knowledge/` (in framework repo) or the data repo, then rewrites:
  - knowledge/retrospectives/INDEX.yaml
  - knowledge/skills/INDEX.md
  - knowledge/solved/INDEX.md
  - knowledge/wp_index/INDEX.md
  - knowledge/INDEX.yaml  (top-level)

Why: multi-machine collaboration → if everyone hand-edits INDEX, conflicts.
Solution: machines only commit content files, this tool builds the index.

Usage:
  python tools/build_kb_index.py              # auto-detect knowledge dir
  python tools/build_kb_index.py --dir <path> # explicit dir
  python tools/build_kb_index.py --check      # exit 1 if INDEX is stale
  python tools/build_kb_index.py --dry-run    # show diff, don't write
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# Windows GBK console fix — must run before any print() with non-ASCII content
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

try:
    import yaml  # type: ignore
except ImportError:
    print("Need pyyaml: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

# ───── Detect knowledge dir ─────

def find_kb_dir(explicit: Path | None) -> Path | None:
    if explicit and (explicit / "knowledge").is_dir():
        return explicit / "knowledge"
    if explicit and explicit.is_dir() and any(p.name in ("retrospectives","solved","skills") for p in explicit.iterdir()):
        return explicit
    # Auto-detect: try common paths
    candidates = [
        Path.cwd() / "knowledge",
        Path(__file__).resolve().parent.parent / "knowledge",
        Path("e:/autoforensicai_data/knowledge"),
        Path("e:/项目/自动化取证/knowledge"),
    ]
    for c in candidates:
        if c.is_dir():
            return c
    return None


# ───── Parse content files ─────

YAML_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)


def parse_yaml(path: Path) -> dict:
    """Parse a .yaml file, returning its dict (or empty)."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        return data if isinstance(data, dict) else {}
    except Exception as e:
        return {"_parse_error": str(e)}


def parse_md_frontmatter(path: Path) -> dict:
    """Parse YAML frontmatter from a .md file."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
        m = YAML_FRONTMATTER_RE.match(text)
        if not m:
            # Take first H1 as title
            for line in text.splitlines():
                if line.startswith("# "):
                    return {"title": line[2:].strip()}
            return {}
        data = yaml.safe_load(m.group(1))
        return data if isinstance(data, dict) else {}
    except Exception as e:
        return {"_parse_error": str(e)}


# ───── Filename suffix parser (machine ID) ─────

MACHINE_SUFFIX_RE = re.compile(r"^(.*?)__([A-Za-z0-9_-]+)(\.[^.]+)$")


def parse_filename(name: str) -> tuple[str, str | None]:
    """Split 'foo__machineA.yaml' → ('foo.yaml', 'machineA')."""
    m = MACHINE_SUFFIX_RE.match(name)
    if not m:
        return name, None
    base, machine, ext = m.groups()
    return base + ext, machine


# ───── Index builders ─────

def build_retrospectives_index(rdir: Path) -> dict:
    """Scan retrospectives/, return INDEX dict."""
    entries: list[dict] = []
    for p in sorted(rdir.glob("**/*.yaml")):
        if p.name.upper() == "INDEX.YAML":
            continue
        data = parse_yaml(p)
        rel = p.relative_to(rdir).as_posix()
        base, machine = parse_filename(p.name)
        entries.append({
            "file": rel,
            "title": data.get("title") or data.get("name") or p.stem,
            "machine": machine or data.get("machine"),
            "date": data.get("date"),
            "tags": data.get("tags", []),
            "category": data.get("category"),
            "role": data.get("role"),
        })
    return {
        "_generated_by": "tools/build_kb_index.py",
        "_count": len(entries),
        "entries": entries,
    }


def build_md_index(mdir: Path, title: str) -> str:
    """Generic markdown directory index."""
    files = sorted([
        p for p in mdir.glob("**/*.md")
        if p.name.upper() != "INDEX.MD" and not p.name.startswith(".")
    ])
    lines = [f"# {title}", "", f"_Auto-generated by `tools/build_kb_index.py`. Do not hand-edit._", "", f"Total: **{len(files)}** entries", ""]
    # Group by parent dir
    groups: dict[str, list[Path]] = {}
    for f in files:
        rel_parent = f.parent.relative_to(mdir).as_posix() or "."
        groups.setdefault(rel_parent, []).append(f)
    for parent, items in sorted(groups.items()):
        if parent != ".":
            lines.append(f"## {parent}")
            lines.append("")
        for f in items:
            data = parse_md_frontmatter(f)
            t = data.get("title") or f.stem
            tags = data.get("tags") or []
            tags_str = " · ".join(f"`{t}`" for t in tags) if tags else ""
            rel = f.relative_to(mdir).as_posix()
            lines.append(f"- [{t}]({rel}){' — ' + tags_str if tags_str else ''}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_top_index(kb_root: Path) -> dict:
    """Top-level knowledge/INDEX.yaml — overview."""
    sections = {}
    for sub in sorted(kb_root.iterdir()):
        if not sub.is_dir() or sub.name.startswith("."):
            continue
        files = [p for p in sub.glob("**/*") if p.is_file() and not p.name.startswith(".") and p.name.upper() not in ("INDEX.YAML","INDEX.MD")]
        sections[sub.name] = {
            "count": len(files),
            "kinds": list(sorted(set(p.suffix for p in files if p.suffix))),
        }
    return {
        "_generated_by": "tools/build_kb_index.py",
        "sections": sections,
    }


# ───── Write helpers ─────

def write_yaml(path: Path, data: dict, dry: bool, label: str) -> bool:
    new_text = "# Auto-generated. Do not hand-edit.\n" + yaml.safe_dump(
        data, allow_unicode=True, sort_keys=False, default_flow_style=False
    )
    old_text = path.read_text(encoding="utf-8") if path.exists() else ""
    if new_text == old_text:
        print(f"  - {label}: unchanged")
        return False
    if dry:
        print(f"  ! {label}: WOULD UPDATE ({len(new_text) - len(old_text):+d} bytes)")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"  ✓ {label}: updated ({len(new_text)} bytes)")
    return True


def write_md(path: Path, text: str, dry: bool, label: str) -> bool:
    old_text = path.read_text(encoding="utf-8") if path.exists() else ""
    if text == old_text:
        print(f"  - {label}: unchanged")
        return False
    if dry:
        print(f"  ! {label}: WOULD UPDATE ({len(text) - len(old_text):+d} bytes)")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"  ✓ {label}: updated ({len(text)} bytes)")
    return True


# ───── Main ─────

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", type=Path, help="root containing knowledge/")
    ap.add_argument("--check", action="store_true", help="exit 1 if INDEX is stale (no write)")
    ap.add_argument("--dry-run", action="store_true", help="show what would change, don't write")
    args = ap.parse_args()

    kb_dir = find_kb_dir(args.dir)
    if not kb_dir:
        print("ERR: knowledge/ directory not found. Use --dir.", file=sys.stderr)
        return 2
    print(f"== build_kb_index ==  scanning: {kb_dir}")
    print()

    dry = args.dry_run or args.check
    changed = False

    # 1. Retrospectives
    rdir = kb_dir / "retrospectives"
    if rdir.is_dir():
        idx = build_retrospectives_index(rdir)
        changed |= write_yaml(rdir / "INDEX.yaml", idx, dry, "retrospectives/INDEX.yaml")

    # 2. Skills (markdown)
    sdir = kb_dir / "skills"
    if sdir.is_dir():
        text = build_md_index(sdir, "Skills & Quick References")
        changed |= write_md(sdir / "INDEX.md", text, dry, "skills/INDEX.md")

    # 3. Solved
    soldir = kb_dir / "solved"
    if soldir.is_dir():
        text = build_md_index(soldir, "Solved Problems Library")
        changed |= write_md(soldir / "INDEX.md", text, dry, "solved/INDEX.md")

    # 4. Cards
    cdir = kb_dir / "cards"
    if cdir.is_dir():
        text = build_md_index(cdir, "Resource Cards")
        changed |= write_md(cdir / "INDEX.md", text, dry, "cards/INDEX.md")

    # 5. wp_index
    wdir = kb_dir / "wp_index"
    if wdir.is_dir():
        text = build_md_index(wdir, "Competition Index")
        changed |= write_md(wdir / "INDEX.md", text, dry, "wp_index/INDEX.md")

    # 6. Top-level
    top = build_top_index(kb_dir)
    changed |= write_yaml(kb_dir / "INDEX.yaml", top, dry, "knowledge/INDEX.yaml")

    print()
    if args.check:
        if changed:
            print("STALE: INDEX needs rebuild. Run without --check to update.", file=sys.stderr)
            return 1
        print("OK: all INDEX files up-to-date")
        return 0
    if dry:
        print(f"DRY-RUN: {'changes pending' if changed else 'all up-to-date'}")
    else:
        print(f"DONE: {'updated' if changed else 'no changes'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
